// src/app/components/header/header.component.ts
import { ViewportScroller } from '@angular/common';
import { Component, ElementRef, ViewChild } from '@angular/core';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss']
})
export class HeaderComponent {

  //@ViewChild('header')
  //private headerElement: ElementRef;

  @ViewChild('navcontent')
  private content: ElementRef;

  private isopen: boolean = false;

  constructor(private viewportScroller: ViewportScroller) {
    /*document.addEventListener('scroll', (e) => {
      const topPosition = this.viewportScroller.getScrollPosition()[1];
      if (topPosition > 75) {
        this.headerElement.nativeElement.classList.add("gradient");
      } else {
        this.headerElement.nativeElement.classList.remove("gradient");
      }
    })*/
  }

  scrollTop() {
    this.viewportScroller.scrollToPosition([0, 0]);
  }

  toogleMenu() {
    if(this.isopen) {
      this.close()
    } else {
      this.open()
    }
  }

  close() {
    this.content.nativeElement.classList.add("hidden");
    this.isopen = false;
  }

  open() {
    this.content.nativeElement.classList.remove("hidden");
    this.isopen = true;
  }
}

<nav #header class="fixed w-full z-30 top-0 text-white">
    <div class="w-full container mx-auto flex flex-wrap items-center justify-between mt-0 py-2">
      <div class="pl-4 flex items-center">
        <a class="toggleColour text-white no-underline hover:no-underline font-bold text-xl" (click)="scrollTop()">
          <img src="./assets/logos/espaco-nat-quadrado-branco.png" width="50px" alt="Logo do Espaço Natália Toledo"/>
        </a>
      </div>
      <div class="block lg:hidden pr-4">
        <button class="flex items-center p-1 text-white hover:text-gray-900 focus:outline-none focus:shadow-outline transform transition hover:scale-105 duration-300 ease-in-out" (click)="toogleMenu()">
          <svg class="fill-current h-6 w-6" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
            <title>Menu</title>
            <path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z" />
          </svg>
        </button>
      </div>
      <div class="w-full flex-grow lg:flex lg:items-center lg:w-auto hidden mt-2 lg:mt-0 gradient md:bg-transparent text-black p-4 lg:p-0 z-20" #navcontent>
        <ul class="list-reset lg:flex justify-end flex-1 items-center">
          <li class="mr-3">
            <a class="inline-block text-white hover:underline hover:underline-offset-8 py-2 px-4" [routerLink]="['']" (click)="scrollTop(); close()">Início</a>
          </li>
          <li class="mr-3">
            <a class="inline-block text-white hover:underline hover:underline-offset-8 py-2 px-4" [routerLink]="['']" fragment="servicos" (click)="close()">Serviços</a>
          </li>
          <li class="mr-3">
            <a class="inline-block text-white hover:underline hover:underline-offset-8 py-2 px-4" [routerLink]="['']" fragment="equipe" (click)="close()">Equipe</a>
          </li>
          <li class="mr-3">
            <a class="inline-block text-white hover:underline hover:underline-offset-8 py-2 px-4" [routerLink]="['']" fragment="espaco" (click)="close()">Espaço</a>
          </li>
          <li class="mr-3">
            <a class="inline-block text-white hover:underline hover:underline-offset-8 py-2 px-4" [routerLink]="['']" fragment="convenios" (click)="close()">Convênios</a>
          </li>
          <li class="mr-3">
            <a class="inline-block text-white hover:underline hover:underline-offset-8 py-2 px-4" [routerLink]="['']" fragment="depoimentos" (click)="close()">Depoimentos</a>
          </li>
          <li class="mr-3">
            <a class="inline-block text-white hover:underline hover:underline-offset-8 py-2 px-4" [routerLink]="['']" fragment="contato" (click)="close()">Contatos</a>
          </li>
        </ul>
        <app-whatsapp></app-whatsapp>
      </div>
    </div>
    <hr class="border-b border-gray-100 opacity-25 my-0 py-0" />
</nav>

// src/components/Header.tsx
'use client';

import { useState } from 'react';
import Image from 'next/image';
import WhatsApp from './WhatsApp';

export default function Header() {
  const [isMenuOpen, setIsMenuOpen] = useState(false);

  const scrollTop = () => {
    window.scrollTo({ top: 0, behavior: 'smooth' });
  };

  const scrollToSection = (sectionId: string) => {
    const element = document.getElementById(sectionId);
    if (element) {
      const offset = 100; // Account for fixed header
      const elementPosition = element.offsetTop - offset;
      window.scrollTo({ top: elementPosition, behavior: 'smooth' });
    }
    setIsMenuOpen(false);
  };

  const toggleMenu = () => {
    setIsMenuOpen(!isMenuOpen);
  };

  return (
    <nav className="fixed w-full z-30 top-0 text-white gradient">
      <div className="w-full container mx-auto flex flex-wrap items-center justify-between mt-0 py-2">
        <div className="pl-4 flex items-center">
          <a 
            className="toggleColour text-white no-underline hover:no-underline font-bold text-xl cursor-pointer" 
            onClick={scrollTop}
          >
            <Image 
              src="/assets/logos/espaco-nat-quadrado-branco.png" 
              width={50} 
              height={50} 
              alt="Logo do Espaço Natália Toledo"
            />
          </a>
        </div>
        
        <div className="block lg:hidden pr-4">
          <button 
            className="flex items-center p-1 text-white hover:text-gray-900 focus:outline-none focus:shadow-outline transform transition hover:scale-105 duration-300 ease-in-out" 
            onClick={toggleMenu}
          >
            <svg className="fill-current h-6 w-6" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
              <title>Menu</title>
              <path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z" />
            </svg>
          </button>
        </div>
        
        <div className={`w-full flex-grow lg:flex lg:items-center lg:w-auto ${isMenuOpen ? '' : 'hidden'} mt-2 lg:mt-0 text-black p-4 lg:p-0 z-20`}>
          <ul className="list-reset lg:flex justify-end flex-1 items-center">
            <li className="mr-3">
              <a 
                className="inline-block text-white hover:underline hover:underline-offset-8 py-2 px-4 cursor-pointer" 
                onClick={() => { scrollTop(); setIsMenuOpen(false); }}
              >
                Início
              </a>
            </li>
            <li className="mr-3">
              <a 
                className="inline-block text-white hover:underline hover:underline-offset-8 py-2 px-4 cursor-pointer" 
                onClick={() => scrollToSection('servicos')}
              >
                Serviços
              </a>
            </li>
            <li className="mr-3">
              <a 
                className="inline-block text-white hover:underline hover:underline-offset-8 py-2 px-4 cursor-pointer" 
                onClick={() => scrollToSection('equipe')}
              >
                Equipe
              </a>
            </li>
            <li className="mr-3">
              <a 
                className="inline-block text-white hover:underline hover:underline-offset-8 py-2 px-4 cursor-pointer" 
                onClick={() => scrollToSection('espaco')}
              >
                Espaço
              </a>
            </li>
            <li className="mr-3">
              <a 
                className="inline-block text-white hover:underline hover:underline-offset-8 py-2 px-4 cursor-pointer" 
                onClick={() => scrollToSection('convenios')}
              >
                Convênios
              </a>
            </li>
            <li className="mr-3">
              <a 
                className="inline-block text-white hover:underline hover:underline-offset-8 py-2 px-4 cursor-pointer" 
                onClick={() => scrollToSection('depoimentos')}
              >
                Depoimentos
              </a>
            </li>
            <li className="mr-3">
              <a 
                className="inline-block text-white hover:underline hover:underline-offset-8 py-2 px-4 cursor-pointer" 
                onClick={() => scrollToSection('contato')}
              >
                Contatos
              </a>
            </li>
          </ul>
          <WhatsApp />
        </div>
      </div>
    </nav>
  );
}
